version: 2.1

jobs:
  clj-test:
    docker:
      - image: cimg/clojure:1.11.1

    steps:
      - checkout
      - restore_cache:
          key: clj-{{ checksum "deps.edn" }}
      - run:
          name: Run tests
          command: ./bin/kaocha --reporter kaocha.report/documentation --plugin profiling --plugin kaocha.plugin/junit-xml --junit-xml-file test-results/kaocha/results.xml
      - store_test_results:
          path: test-results
      - save_cache:
          paths:
            - ~/.m2
            - ~/.gitlibs
          key: clj-{{ checksum "deps.edn" }}

workflows:
  version: 2
  main-workflow:
    jobs:
      - clj-test
